export const RADIUS = 6378137;
export const FLATTENING = 1 / 298.257223563;
export const POLAR_RADIUS = RADIUS * (1 - FLATTENING);
export const FIRST_ECCENTRICITY = Math.sqrt((RADIUS * RADIUS - POLAR_RADIUS * POLAR_RADIUS) / RADIUS * RADIUS);
export const SECOND_ECCENTRICITY = Math.sqrt((RADIUS * RADIUS - POLAR_RADIUS * POLAR_RADIUS) / POLAR_RADIUS * POLAR_RADIUS);
